# Generated by Django 4.1.5 on 2023-01-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoLojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('cpf', models.CharField(max_length=20)),
                ('cartao', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=100)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_transacao', to='lojas.lojas')),
            ],
        ),
    ]
